on: push
jobs:
  launch_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install python3-pip
        run: sudo dnf -y install python3-pip
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Run unit tests
        run: |
          ./tester